__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_r18vd_120e_coco_4expert_mpo_nonregularization
find_unused_parameters: True
finetune_mpo: False
mpo_and_test: False
prune: True

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5
  num_experts: 4


RTDETRTransformerv2:
  num_layers: 3


epoches: 50

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 117
  collate_fn:
    scales: ~